/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Header from "../components/Header/Header";
import About from "./About/About";
import Home from "./Homepage/Home";
import Services from "./ServicesPage/Services";

import dynamic from "next/dynamic";
import ProjectReact from "./ProjectsPage/ProjectReact";
import ProjectWP from "./ProjectsPage/ProjectWP";
import Skills from "./SkillsPage/Skills";
import MyTitle from "../components/MyTitle";
import Experiences from "./Experiences";
import MyContactForm from "../components/MyContactForm";
import MyClipboard from "../components/MyClipBoard/index";

export default function App() {
  // const Slider = dynamic(() => import("../pages/Slider/Slider"), {
  //   ssr: false,
  // });

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <Home />
      <About />
      <Services />
      <ProjectReact />
      <ProjectWP />
      <MyTitle title="Mes compétences" />
      <Skills />

      <Experiences />
      <MyClipboard />
      {/* <MyContactForm /> */}
    </>
  );
}
