/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Header from "../components/Header";
import About from "./About/About";
import Home from "./Home/Home";
import Services from "./Services/Services";

import dynamic from "next/dynamic";
import Projects from "./Projects/Projects";

export default function App() {
  const Slider = dynamic(() => import("../pages/Slider/Slider"), {
    ssr: false,
  });
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Header />
      <Home />
      <About />
      <Services />
      <Projects />
      {/* <Slider /> */}
    </div>
  );
}
